### ISSUE TITLE
Booknlp runs into HTTP Error 404: Not Found when downloading model

### ISSUE THREAD

**Issue by DrewThomasson** [DrewThomasson/VoxNovel#23]
(booknlp) drew@wmughal-CN4D09397T VoxNovel % python gui_run.py 
using device cpu
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/drew/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
1% Converting input to HTML...
InputFormatPlugin: EPUB Input running
on /Users/drew/VoxNovel/Working_files/mini_story_long - Drew.epub
Found HTML cover titlepage.xhtml
Parsing all content...
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
	Detected chapter: Chapter 1: It Continues
	Detected chapter: Chapter 2: The Silk Road Odyssey
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating TXT Output...
67% Running TXT Output plugin
Converting XHTML to TXT...
TXT output written to /Users/drew/VoxNovel/Working_files/mini_story_long - Drew.txt
Output saved to   /Users/drew/VoxNovel/Working_files/mini_story_long - Drew.txt
{'pipeline': 'entity,quote,supersense,event,coref', 'model': 'big'}
downloading entities_google_bert_uncased_L-6_H-768_A-12-v1.0.model
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/drew/VoxNovel/gui_run.py", line 432, in process_file
    booknlp = BookNLP("en", model_params)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/site-packages/booknlp/booknlp.py", line 14, in __init__
    self.booknlp=EnglishBookNLP(model_params)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/site-packages/booknlp/english/english_booknlp.py", line 63, in __init__
    urllib.request.urlretrieve("http://ischool.berkeley.edu/~dbamman/booknlp_models/%s" % entityName, self.entityPath)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/drew/miniconda3/envs/booknlp/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by DrewThomasson** [comment]
Idk what happened but at this moment in time the models for Booknlp won't download, 

The pages are down?? it's super weird

**Comment by DrewThomasson** [comment]
I backed up the booknlp models here so :)


https://huggingface.co/drewThomasson/Booknlp_models_Backup

**Comment by DrewThomasson** [comment]
temp fix: 

run the 

download_missing_booknlp_models.py

file included in the github repo

that should give you the files, using my huggingface repo
